# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(650, 525)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #e5e0e4;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.color_label = QtWidgets.QLabel(self.centralwidget)
        self.color_label.setGeometry(QtCore.QRect(240, 180, 141, 81))
        self.color_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(93,93,93);")
        self.color_label.setText("")
        self.color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.color_label.setObjectName("color_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(390, 0, 251, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.rgba_sliders_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.rgba_sliders_layout.setContentsMargins(0, 0, 0, 0)
        self.rgba_sliders_layout.setObjectName("rgba_sliders_layout")
        self.alpha_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.alpha_slider.setStyleSheet("QSlider{\n"
"                background: #E3DEE2;\n"
"            }\n"
"            QSlider::groove:horizontal {\n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_slider.setObjectName("alpha_slider")
        self.rgba_sliders_layout.addWidget(self.alpha_slider, 3, 0, 1, 1)
        self.red_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.red_slider.setStyleSheet("QSlider{\n"
"                background: #E3DEE2;\n"
"            }\n"
"            QSlider::groove:horizontal {\n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.red_slider.setOrientation(QtCore.Qt.Horizontal)
        self.red_slider.setObjectName("red_slider")
        self.rgba_sliders_layout.addWidget(self.red_slider, 0, 0, 1, 1)
        self.blue_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.blue_slider.setStyleSheet("QSlider{\n"
"                background: #E3DEE2;\n"
"            }\n"
"            QSlider::groove:horizontal {\n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.blue_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blue_slider.setObjectName("blue_slider")
        self.rgba_sliders_layout.addWidget(self.blue_slider, 2, 0, 1, 1)
        self.green_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.green_slider.setStyleSheet("QSlider{\n"
"                background: #E3DEE2;\n"
"            }\n"
"            QSlider::groove:horizontal {\n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.green_slider.setOrientation(QtCore.Qt.Horizontal)
        self.green_slider.setObjectName("green_slider")
        self.rgba_sliders_layout.addWidget(self.green_slider, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 0, 141, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.rgba_inputs_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.rgba_inputs_layout.setContentsMargins(0, 0, 0, 0)
        self.rgba_inputs_layout.setObjectName("rgba_inputs_layout")
        self.green_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.green_input.setFont(font)
        self.green_input.setMaxLength(3)
        self.green_input.setAlignment(QtCore.Qt.AlignCenter)
        self.green_input.setObjectName("green_input")
        self.rgba_inputs_layout.addWidget(self.green_input, 1, 1, 1, 1)
        self.blue_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.blue_input.setFont(font)
        self.blue_input.setMaxLength(3)
        self.blue_input.setAlignment(QtCore.Qt.AlignCenter)
        self.blue_input.setObjectName("blue_input")
        self.rgba_inputs_layout.addWidget(self.blue_input, 2, 1, 1, 1)
        self.alpha_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.alpha_input.setFont(font)
        self.alpha_input.setMaxLength(3)
        self.alpha_input.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_input.setObjectName("alpha_input")
        self.rgba_inputs_layout.addWidget(self.alpha_input, 3, 1, 1, 1)
        self.red_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.red_input.setFont(font)
        self.red_input.setMaxLength(3)
        self.red_input.setAlignment(QtCore.Qt.AlignCenter)
        self.red_input.setObjectName("red_input")
        self.rgba_inputs_layout.addWidget(self.red_input, 0, 1, 1, 1)
        self.red_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.red_label.setFont(font)
        self.red_label.setObjectName("red_label")
        self.rgba_inputs_layout.addWidget(self.red_label, 0, 0, 1, 1)
        self.green_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.green_label.setFont(font)
        self.green_label.setObjectName("green_label")
        self.rgba_inputs_layout.addWidget(self.green_label, 1, 0, 1, 1)
        self.blue_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.blue_label.setFont(font)
        self.blue_label.setObjectName("blue_label")
        self.rgba_inputs_layout.addWidget(self.blue_label, 2, 0, 1, 1)
        self.alpha_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.alpha_label.setFont(font)
        self.alpha_label.setObjectName("alpha_label")
        self.rgba_inputs_layout.addWidget(self.alpha_label, 3, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(390, 180, 251, 128))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.toolbar_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.toolbar_layout.setContentsMargins(0, 0, 0, 0)
        self.toolbar_layout.setSpacing(6)
        self.toolbar_layout.setObjectName("toolbar_layout")
        self.invert_text_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.invert_text_button.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.invert_text_button.setFont(font)
        self.invert_text_button.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;\n"
"color: white;")
        self.invert_text_button.setIconSize(QtCore.QSize(30, 32))
        self.invert_text_button.setObjectName("invert_text_button")
        self.toolbar_layout.addWidget(self.invert_text_button, 1, 1, 1, 1)
        self.copy_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.copy_button.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;")
        self.copy_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_button.setIcon(icon1)
        self.copy_button.setIconSize(QtCore.QSize(28, 32))
        self.copy_button.setObjectName("copy_button")
        self.toolbar_layout.addWidget(self.copy_button, 0, 0, 1, 1)
        self.color_output_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.color_output_input.setFont(font)
        self.color_output_input.setMaxLength(100)
        self.color_output_input.setAlignment(QtCore.Qt.AlignCenter)
        self.color_output_input.setObjectName("color_output_input")
        self.toolbar_layout.addWidget(self.color_output_input, 0, 1, 1, 1)
        self.random_color_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.random_color_button.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;")
        self.random_color_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/dice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.random_color_button.setIcon(icon2)
        self.random_color_button.setIconSize(QtCore.QSize(28, 32))
        self.random_color_button.setAutoRepeat(False)
        self.random_color_button.setAutoExclusive(False)
        self.random_color_button.setDefault(False)
        self.random_color_button.setFlat(False)
        self.random_color_button.setObjectName("random_color_button")
        self.toolbar_layout.addWidget(self.random_color_button, 2, 0, 1, 1)
        self.invert_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.invert_button.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;")
        self.invert_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/invert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.invert_button.setIcon(icon3)
        self.invert_button.setIconSize(QtCore.QSize(28, 32))
        self.invert_button.setObjectName("invert_button")
        self.toolbar_layout.addWidget(self.invert_button, 1, 0, 1, 1)
        self.random_color_text_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.random_color_text_button.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.random_color_text_button.setFont(font)
        self.random_color_text_button.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;\n"
"color: white;")
        self.random_color_text_button.setIconSize(QtCore.QSize(30, 32))
        self.random_color_text_button.setObjectName("random_color_text_button")
        self.toolbar_layout.addWidget(self.random_color_text_button, 2, 1, 1, 1)
        self.color_converter_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.color_converter_comboBox.setGeometry(QtCore.QRect(240, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.color_converter_comboBox.setFont(font)
        self.color_converter_comboBox.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;\n"
"color: white;")
        self.color_converter_comboBox.setObjectName("color_converter_comboBox")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_converter_comboBox.addItem("")
        self.color_history_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.color_history_groupBox.setGeometry(QtCore.QRect(240, 320, 401, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.color_history_groupBox.setFont(font)
        self.color_history_groupBox.setStyleSheet("background-color: rgb(93,93,93);\n"
"border: 4 px solid rgb(93,93,93);\n"
"color: white;\n"
"border-radius: 10px;\n"
"")
        self.color_history_groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.color_history_groupBox.setFlat(False)
        self.color_history_groupBox.setObjectName("color_history_groupBox")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.color_history_groupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(9, 40, 381, 111))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setHorizontalSpacing(28)
        self.gridLayout.setObjectName("gridLayout")
        self.history_color_button_6 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_6.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_6.setText("")
        self.history_color_button_6.setObjectName("history_color_button_6")
        self.gridLayout.addWidget(self.history_color_button_6, 0, 5, 1, 1)
        self.history_color_button_1 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_1.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_1.setText("")
        self.history_color_button_1.setObjectName("history_color_button_1")
        self.gridLayout.addWidget(self.history_color_button_1, 0, 0, 1, 1)
        self.history_color_button_3 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_3.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_3.setText("")
        self.history_color_button_3.setObjectName("history_color_button_3")
        self.gridLayout.addWidget(self.history_color_button_3, 0, 2, 1, 1)
        self.history_color_button_5 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_5.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_5.setText("")
        self.history_color_button_5.setObjectName("history_color_button_5")
        self.gridLayout.addWidget(self.history_color_button_5, 0, 4, 1, 1)
        self.history_color_button_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_2.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_2.setText("")
        self.history_color_button_2.setObjectName("history_color_button_2")
        self.gridLayout.addWidget(self.history_color_button_2, 0, 1, 1, 1)
        self.history_color_button_4 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_4.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_4.setText("")
        self.history_color_button_4.setObjectName("history_color_button_4")
        self.gridLayout.addWidget(self.history_color_button_4, 0, 3, 1, 1)
        self.history_color_button_7 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_7.setMinimumSize(QtCore.QSize(0, 36))
        self.history_color_button_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_7.setText("")
        self.history_color_button_7.setObjectName("history_color_button_7")
        self.gridLayout.addWidget(self.history_color_button_7, 1, 0, 1, 1)
        self.history_color_button_8 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_8.setMinimumSize(QtCore.QSize(0, 36))
        self.history_color_button_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_8.setText("")
        self.history_color_button_8.setObjectName("history_color_button_8")
        self.gridLayout.addWidget(self.history_color_button_8, 1, 1, 1, 1)
        self.history_color_button_9 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_9.setMinimumSize(QtCore.QSize(0, 36))
        self.history_color_button_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_9.setText("")
        self.history_color_button_9.setObjectName("history_color_button_9")
        self.gridLayout.addWidget(self.history_color_button_9, 1, 2, 1, 1)
        self.history_color_button_10 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_10.setMinimumSize(QtCore.QSize(0, 36))
        self.history_color_button_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_10.setText("")
        self.history_color_button_10.setObjectName("history_color_button_10")
        self.gridLayout.addWidget(self.history_color_button_10, 1, 3, 1, 1)
        self.history_color_button_11 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_11.setMinimumSize(QtCore.QSize(32, 36))
        self.history_color_button_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_11.setText("")
        self.history_color_button_11.setObjectName("history_color_button_11")
        self.gridLayout.addWidget(self.history_color_button_11, 1, 4, 1, 1)
        self.history_color_button_12 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.history_color_button_12.setMinimumSize(QtCore.QSize(0, 36))
        self.history_color_button_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_color_button_12.setText("")
        self.history_color_button_12.setObjectName("history_color_button_12")
        self.gridLayout.addWidget(self.history_color_button_12, 1, 5, 1, 1)
        self.zoom_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.zoom_comboBox.setGeometry(QtCore.QRect(50, 450, 171, 34))
        self.zoom_comboBox.setMinimumSize(QtCore.QSize(0, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zoom_comboBox.setFont(font)
        self.zoom_comboBox.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;\n"
"color: white;")
        self.zoom_comboBox.setObjectName("zoom_comboBox")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.zoom_comboBox.addItem("")
        self.eyedropper_button = QtWidgets.QPushButton(self.centralwidget)
        self.eyedropper_button.setGeometry(QtCore.QRect(10, 450, 34, 34))
        self.eyedropper_button.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;")
        self.eyedropper_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/empty_eyedropper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eyedropper_button.setIcon(icon4)
        self.eyedropper_button.setIconSize(QtCore.QSize(28, 32))
        self.eyedropper_button.setAutoRepeat(False)
        self.eyedropper_button.setAutoExclusive(False)
        self.eyedropper_button.setDefault(False)
        self.eyedropper_button.setFlat(False)
        self.eyedropper_button.setObjectName("eyedropper_button")
        self.color_wheel_label = QtWidgets.QLabel(self.centralwidget)
        self.color_wheel_label.setGeometry(QtCore.QRect(10, 0, 211, 211))
        self.color_wheel_label.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;")
        self.color_wheel_label.setText("")
        self.color_wheel_label.setPixmap(QtGui.QPixmap(":/Icons/color_wheel.png"))
        self.color_wheel_label.setScaledContents(True)
        self.color_wheel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.color_wheel_label.setObjectName("color_wheel_label")
        self.screen_widget = QtWidgets.QWidget(self.centralwidget)
        self.screen_widget.setGeometry(QtCore.QRect(9, 229, 211, 211))
        self.screen_widget.setStyleSheet("background-color: rgb(93,93,93);\n"
"border-radius: 10px;")
        self.screen_widget.setObjectName("screen_widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.zoom_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.green_input.setText(_translate("MainWindow", "0"))
        self.blue_input.setText(_translate("MainWindow", "0"))
        self.alpha_input.setText(_translate("MainWindow", "0"))
        self.red_input.setText(_translate("MainWindow", "0"))
        self.red_label.setText(_translate("MainWindow", "Red"))
        self.green_label.setText(_translate("MainWindow", "Green"))
        self.blue_label.setText(_translate("MainWindow", "Blue"))
        self.alpha_label.setText(_translate("MainWindow", "Alpha"))
        self.invert_text_button.setText(_translate("MainWindow", "Інвертувати значення"))
        self.color_output_input.setText(_translate("MainWindow", "0, 0, 0"))
        self.random_color_text_button.setText(_translate("MainWindow", "Випадковий колір"))
        self.color_converter_comboBox.setCurrentText(_translate("MainWindow", "RGB-значення"))
        self.color_converter_comboBox.setItemText(0, _translate("MainWindow", "RGB-значення"))
        self.color_converter_comboBox.setItemText(1, _translate("MainWindow", "RGBA-значення"))
        self.color_converter_comboBox.setItemText(2, _translate("MainWindow", "HSL"))
        self.color_converter_comboBox.setItemText(3, _translate("MainWindow", "HTML Hex"))
        self.color_converter_comboBox.setItemText(4, _translate("MainWindow", "Delphi Hex"))
        self.color_converter_comboBox.setItemText(5, _translate("MainWindow", "CMY"))
        self.color_converter_comboBox.setItemText(6, _translate("MainWindow", "CMYK"))
        self.color_converter_comboBox.setItemText(7, _translate("MainWindow", "CSS RGBA"))
        self.color_history_groupBox.setTitle(_translate("MainWindow", "                   Останні використовувані кольори                 "))
        self.zoom_comboBox.setCurrentText(_translate("MainWindow", "Приближення х1"))
        self.zoom_comboBox.setItemText(0, _translate("MainWindow", "Приближення х1"))
        self.zoom_comboBox.setItemText(1, _translate("MainWindow", "Приближення х2"))
        self.zoom_comboBox.setItemText(2, _translate("MainWindow", "Приближення х3"))
        self.zoom_comboBox.setItemText(3, _translate("MainWindow", "Приближення х4"))
        self.zoom_comboBox.setItemText(4, _translate("MainWindow", "Приближення х5"))
        self.zoom_comboBox.setItemText(5, _translate("MainWindow", "Приближення х6"))
        self.zoom_comboBox.setItemText(6, _translate("MainWindow", "Приближення х7"))
        self.zoom_comboBox.setItemText(7, _translate("MainWindow", "Приближення х8"))
        self.zoom_comboBox.setItemText(8, _translate("MainWindow", "Приближення х9"))
        self.zoom_comboBox.setItemText(9, _translate("MainWindow", "Приближення х10"))
import Resources_rc



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
